version: "3.8"

services:
  wato_research_kinova:
    build:
      context: .
      dockerfile: docker/server/Kinova.Dockerfile
    image: wato-research-kinova:latest
    # command: /bin/bash -c "python -u kinova.py"
    restart: always
    command: tail -f /dev/null
    # volumes:
    #   - ./src/server:/home/wato_research
  
  wato_research_agent:
    build:
      context: .
      dockerfile: docker/client/Agent.Dockerfile
    image: wato-research-agent:latest
    # command: /bin/bash -c "python -u evaluate.py"
    command: tail -f /dev/null
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src/client/rlenv.py:/root/tdmpc2/rlenv.py
      - ./src/client/camera_test.py:/root/tdmpc2/camera_test.py
      # - ./src/client/tdmpc2/tdmpc2/config.yaml:/root/tdmpc2/
      # - ./src/client/tdmpc2/tdmpc2/:/root/tdmpc2/tdmpc2
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video4:/dev/video4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
